name: CI

on:
  push:
    branches:
      - main  # Troque pelo nome do seu branch principal
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set environment variables for testing
        env:
          RPC_URL: ${{ vars.RPC_URL }}
          CHAIN_ID: ${{ vars.CHAIN_ID }}
          PANCAKESWAP_ROUTER_ADDRESS: ${{ vars.PANCAKESWAP_ROUTER_ADDRESS }}
          PANCAKESWAP_ROUTER_ABI: ${{ vars.PANCAKESWAP_ROUTER_ABI }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
        run: |
          echo "RPC_URL: $RPC_URL"
          echo "CHAIN_ID: $CHAIN_ID"
          echo "PANCAKESWAP_ROUTER_ADDRESS: $PANCAKESWAP_ROUTER_ADDRESS"
          echo "PANCAKESWAP_ROUTER_ABI: $PANCAKESWAP_ROUTER_ABI"
          echo "WALLET_ADDRESS: $WALLET_ADDRESS"

      - name: Run tests
        env:  # Configurar as variáveis de ambiente para acesso nos testes
          RPC_URL: ${{ vars.RPC_URL }}  # Variável normal
          CHAIN_ID: ${{ vars.CHAIN_ID }}  # Variável normal
          PANCAKESWAP_ROUTER_ADDRESS: ${{ vars.PANCAKESWAP_ROUTER_ADDRESS }}  # Variável normal
          PANCAKESWAP_ROUTER_ABI: ${{ vars.PANCAKESWAP_ROUTER_ABI }}  # Variável normal
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}  # Secret
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}  # Secret
        run: |
          poetry run pytest -v